apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80


        ERROR: failed to solve: process "/bin/sh -c useradd -l -u ${UID} -d /home/user -s /bin/bash user &&     echo \"user ALL=(ALL) NOPASSWD:ALL\" > /etc/sudoers.d/user &&     mkdir -p /home/user/.kube &&     mkdir -p /home/user/.cache &&     chown -R user /home/user &&     chgrp -R user /home/user &&     HOME=/home/user git config --global user.name \"ArgoCD Test User\" &&     HOME=/home/user git config --global user.email \"noreply@example.com\" &&     mkdir -p /go/pkg &&     mkdir -p /var/run/sshd &&     mkdir -p /root/.ssh &&     mkdir -p /go &&     chown root /etc/ssh/ssh_host_*_key* &&     chmod 0600 /etc/ssh/ssh_host_*_key &&     mkdir -p /tmp/go-build-cache &&     ln -s /usr/local/bin/node /usr/local/bin/nodejs &&     ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm &&     ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx &&     ln -s /opt/yarn-v1.22.19/bin/yarn /usr/local/bin/yarn &&     ln -s /opt/yarn-v1.22.19/bin/yarnpkg /usr/local/bin/yarnpkg &&     mkdir -p /var/lib/registry" did not complete successfully: exit code: 4
make: *** [Makefile:251: test-tools-image] Error 1

