apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Specify a node port within the range 30000-32767
  selector:
    app: guestbook-ui
